### PR TITLE
Updated Serverless Days Jaipur

### PR DESCRIPTION
**Pull request by heyAyushh**
Added event website of ServerlessDays Jaipur

### CODE REVIEW

**Comment by alexcasalboni** [comment]
Hi @heyAyushh, thanks for contributing 🎉 

Could you please use HTTPS for both website and image?

**Comment by alexcasalboni** [comment]
Thanks 💯 

Let's merge this once the website is up and running. CC @antstanley

**Comment by heyAyushh** [comment]
@alexcasalboni the site is up 🙌

**Comment by alexcasalboni** [comment]
Great work, @heyAyushh! 💯

**Comment by heyAyushh** [comment]
@alexcasalboni woohoo

**Pull request merged**
