### PR TITLE
Adding 2023 São Paulo event to events.json

### PR DESCRIPTION
**Pull request by jeanlucaslima**
Hi! 

I added `saopaulo.serverlessdays.io` as URL, but we don't yet have this page set up (but we want to ;-) ).

### CODE REVIEW

**Comment by jeanlucaslima** [comment]
@alexcasalboni how can we add the site? I'm just a bit lost on where to ask for it.

**Comment by alexcasalboni** [comment]
@jeanlucaslima you just publish it wherever you want (CloudFront, Netlify, etc.) and let us have the host so I can create the DNS record for saopaulo.serverlessdays.io :)

**Comment by jeanlucaslima** [comment]
Nice! On it.

**Comment by jeanlucaslima** [comment]
Done on Vercel, got this message:

Another `Vercel` account is using this domain. Please set the following `TXT` record on `_vercel.serverlessdays.io` to use `saopaulo.serverlessdays.io` in this project. Once the verification is completed and the domain is successfully configured, the TXT record can be removed.


```
vc-domain-verify=saopaulo.serverlessdays.io,165ebccf2449b6de9239
```

**Comment by jeanlucaslima** [comment]
Is... Is it possible to have a repo here on ServerlessDays account?

**Comment by alexcasalboni** [comment]
@jeanlucaslima I've added the `_vercel` TXT record.

And also an ALIAS record pointing to `saopaulo-serverlessdays.vercel.app` :)

Let me know once it all works (I believe you need to assign that subdomain to a project on Vercel), then we can merge this PR 👌

**Comment by jeanlucaslima** [comment]
Funny! I didn't know what I needed to do and it was just to log in to vercel. 

It's live! Please let me know if you need to merge.

**Comment by alexcasalboni** [comment]
Just a couple of fixes :) Merging now 🚀

**Pull request merged**
