### PR TITLE
Add Paris Serverlessdays :)

### PR DESCRIPTION
**Pull request by benja-M-1**

### CODE REVIEW

**Comment by alexcasalboni** [comment]
Thanks @benja-M-1! You can see the deployment preview here: https://deploy-preview-96--serverlessdays-dev.netlify.com/

Unfortunately, the event won't show up until you provide an `image` field as well :)

**Comment by benja-M-1** [comment]
@alexcasalboni how can I use cloudinary like others conferences did? I would like to use this image https://unsplash.com/photos/Vi9cHboZwss.

**Comment by benja-M-1** [comment]
@alexcasalboni found a better solution... I resized the image and used a base 64 encoded image in the json file! No need to save the image somewhere...

**Comment by alexcasalboni** [comment]
Great, merging now :)

**Comment by benja-M-1** [comment]
thank you @alexcasalboni :)

**Pull request merged**
