### PR TITLE
Add Serverless Days TLV to the list

### PR DESCRIPTION
**Pull request by adamatan**

### CODE REVIEW

**Comment by alexcasalboni** [comment]
Thanks @adamatan, I'll merge this as soon as the subdomain is active :)

**Comment by adamatan** [comment]
Thanks! A kind reminder that https://tlv.serverlessdays.io/ is active.

**Comment by alexcasalboni** [comment]
@adamatan I didn't merge this PR because you added a new object to the list (there was already an object for SlsDays Tel Aviv in the file). I have opened & merged another PR in the meantime. Closing this one.

**Comment by adamatan** [comment]
Thanks, apologies for missing it.

**Pull request closed without merging**
