### PR TITLE
Add Sao Paulo/BR

### PR DESCRIPTION
**Pull request by mataide**
Add São Paulo event

### CODE REVIEW

**Comment by alexcasalboni** [comment]
Thanks for contributing, @mataide!

It looks like the website & image are not reachable, though.

Can you please double-check? Where did you deploy the website? :)

**Comment by alexcasalboni** [comment]
@mataide ping?

**Comment by alexcasalboni** [comment]
@mataide any updates?

**Comment by jeanlucaslima** [comment]
Hi, I think this issue was abandoned, I'm kicking off a new São Paulo edition (with Evandro and some others). 

@alexcasalboni - what should I do? Create a pull request? Can we make a repo as well for São Paulo?

**Comment by alexcasalboni** [comment]
Closing this issue. We'll merge #176 instead :)

**Pull request closed without merging**
