### PR TITLE
Updated Nashville Location

### PR DESCRIPTION
**Pull request by jabezabraham**
Added upcoming event info with website information.

### CODE REVIEW

**Comment by alexcasalboni** [comment]
Thanks for contributing, @jabezabraham!

Let me know when the website `https://serverlessnashville.io` is live so I can merge this PR :)

Would you like me to create the subdomain `nashville.serverlessdays.io` too?

**Comment by jabezabraham** [comment]
> Thanks for contributing, @jabezabraham!
> 
> Let me know when the website `https://serverlessnashville.io` is live so I can merge this PR :)
> 
> Would you like me to create the subdomain `nashville.serverlessdays.io` too?

@alexcasalboni the website is up and running now.. 👍please merge when you are able to.. 
Also, the domain is hosted as serverlessNashville.io, I am fine either way if you want to have a subdomain as well in the main site.

**Comment by alexcasalboni** [comment]
mmm weird, I still see a `404 Not Found` error

**Comment by alexcasalboni** [comment]
nevermind, now it's ok :)

**Pull request merged**
